#!/usr/bin/env ruby
# encoding: UTF-8

require 'rubygems'
require 'net/https'
require 'json'
require 'optparse'

require_relative 'common/configure'
require_relative 'common/authenticate'
require_relative 'common/http_util'

# Parse command line options
options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: rvn-publish [options]"
  opts.on("-v", "--verbose", "Run verbosely") do |v|
    options[:verbose] = v
  end
  opts.on("-u", "--user=USER", "User name") do |user|
    options[:user] = user
  end
  opts.on("-p", "--password=PASSWORD", "Password") do |password|
    options[:password] = password
  end
  opts.on("-h", "--help", "Display this help") do |help|
    puts opts
    exit 0
  end
end.parse!

def create_domain(config, token)
  base_uri = config[:base_uri]
  domain   = config[:domain]
  uri   = URI.parse("#{base_uri}/service/domains/#{domain}")
  puts "Publishing to URI: #{uri}"
  http  = init_http_object uri

  begin
    request = Net::HTTP::Post.new(uri.request_uri)
    request.add_field 'Cookie', "lfrb-session-auth=#{token}"
    response = http.request(request)
    puts "Response: #{response.code} #{response['Location']}"
  rescue OpenSSL::SSL::SSLError => exception
    handle_exception(uri.to_s, exception)
  rescue JSON::ParserError => exception
    handle_exception(uri.to_s, exception)
  rescue Exception => exception
    handle_exception(uri.to_s, exception)
  end
end

def create_user(config, token)
  base_uri = config[:base_uri]
  domain   = config[:domain]
  uri   = URI.parse("#{base_uri}/service/domains/#{domain}/users")
  puts "Publishing to URI: #{uri}"
  http  = init_http_object uri
  
  user = {:name => config[:user], :password => config[:password], :homeDomain => config[:domain], :email => config[:email]}.to_json

  begin
    request = Net::HTTP::Post.new(uri.request_uri)
    request.add_field 'Cookie', "lfrb-session-auth=#{token}"
    request.add_field 'Content-Type', 'application/json'
    request.body = user
    response = http.request(request)
    puts "Response: #{response.code} #{response['Location']}"
  rescue OpenSSL::SSL::SSLError => exception
    handle_exception(uri.to_s, exception)
  rescue JSON::ParserError => exception
    handle_exception(uri.to_s, exception)
  rescue Exception => exception
    handle_exception(uri.to_s, exception)
  end
end

# BEGIN

config = configure(nil)
puts "Bootstraping for configuration: #{config} using opptions: #{options}"

user_ctx = UserCtx.new options[:user], options[:password]
user_ctx.authenticate config[:base_uri]
token = user_ctx.token

create_domain(config, token)
create_user(config, token)

